train:
  _target_: src.datasets.LibrispeechMixDataset
  part: "train-clean-100"
  segment_size: 32768
  instance_transforms: ${transforms.instance_transforms.train}
  limit: 20000
test:
  _target_: src.datasets.LibrispeechMixDataset
  part: "test-clean"
  segment_size: 32768
  instance_transforms: ${transforms.instance_transforms.train}
  limit: 500
 # limit: 2