_target_: src.utils.nn_utils.HiFiGeneratorBackbone
resblock: "1"
upsample_rates: [8, 8, 2, 2]
upsample_kernel_sizes: [16, 16, 4, 4]
upsample_initial_channel: 128
resblock_kernel_sizes: [3, 7, 11]
resblock_dilation_sizes: [[1, 3, 5], [1, 3, 5], [1, 3, 5]]
conv_pre_kernel_size: 1
input_channels: 80
norm_type: weight
use_istft: False
