defaults:
  - model: hifi
  - writer: wandb
  - metrics: speech_denoising
  - datasets: voice_bank
  - dataloader: example
  - transforms: example
  - _self_
optimizer:
  _target_: torch.optim.Adam
  lr: 3e-4
lr_scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  gamma: 0.9
  step_size: ${trainer.epoch_len}
generator_loss_function:
  _target_: src.loss.GeneratorLoss
discriminator_loss_function:
  _target_: src.loss.DiscriminatorLoss
trainer:
  log_step: 50
  n_epochs: 1000000
  epoch_len: 1
  device_tensors: ["clean_audio", "noisy_audio"] # which tensors should be on device (ex. GPU)
  resume_from: null # null or path to the checkpoint dir with *.pth and config.yaml
  device: auto # device name or "auto"
  override: True # if True, will override the previous run with the same name
  # monitor: "max test_MulticlassAccuracy" # "off" or "max/min metric_name", i.e. our goal is to maximize/minimize metric
  save_period: 50 # checkpoint each save_period epochs in addition to the best epoch
  early_stop: ${trainer.n_epochs} # epochs for early stopping
  save_dir: "saved"
  seed: 1
