defaults:
  - model: bss_v2
  - metrics: bss
  - datasets: librispeech_mix # we do not want to run inference on training data
  - dataloader: example
  - transforms: bss
  - _self_
inferencer:
  device_tensors: ["mix_audio", "audios"] # which tensors should be on device (ex. GPU)
  device: auto # device name or "auto"
  save_path: "example" # any name here, can be a dataset name
  seed: 1
  from_pretrained: D:\HiFi-SS\v2_post_snr_discs-epoch47.pth # path to the pretrained model
