#_target_: src.utils.nn_utils.HiFiGeneratorBackbone
_target_: src.model.generator.istftnet.Generator
resblock: "1"
upsample_rates: [8, 8]
upsample_kernel_sizes: [16, 16]
upsample_initial_channel: 128
resblock_kernel_sizes: [3, 7, 11]
resblock_dilation_sizes: [[1, 3, 5], [1, 3, 5], [1, 3, 5]]
conv_pre_kernel_size: 1
input_channels: 80
#use_istft: True
gen_istft_n_fft: 16
gen_istft_hop_size: 4
