_target_: src.utils.nn_utils.HiFiGeneratorBackbone
resblock: "1"
upsample_rates: [8, 1]
upsample_kernel_sizes: [16, 3]
upsample_initial_channel: 128
resblock_kernel_sizes: [3, 7, 11]
resblock_dilation_sizes: [[1, 3, 5], [1, 3, 5], [1, 3, 5]]
conv_pre_kernel_size: 1
input_channels: 128
use_istft: True
gen_istft_n_fft: 128
gen_istft_hop_size: 32