train:
  clean_audio:
    _target_: src.transforms.Shrink
    factor: 1024
  noisy_audio:
    _target_: src.transforms.Shrink
    factor: 1024
inference:
  clean_audio:
    _target_: src.transforms.Shrink
    factor: 1024
  noisy_audio:
    _target_: src.transforms.Shrink
    factor: 1024
